CREATE OR REPLACE TRIGGER ASZTAL_TRIGGER
BEFORE INSERT OR DELETE OR UPDATE ON ASZTAL FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO DATA_LOG VALUES(CURRENT_TIMESTAMP, 'BESZURAS', 'ASZTAL');
    END IF;
    IF DELETING THEN
        INSERT INTO DATA_LOG VALUES(CURRENT_TIMESTAMP, 'TORLES', 'ASZTAL');
    END IF;
    IF UPDATING THEN
        INSERT INTO DATA_LOG VALUES(CURRENT_TIMESTAMP, 'MODOSITAS', 'ASZTAL');
    END IF;
END;
