DECLARE
    P_ID PINCER.PINCERID%TYPE;
    P_NEV PINCER.NEV%TYPE;
    P_FIZ PINCER.FIZETES%TYPE;
    P_KOR PINCER.KOR%TYPE;
    P_KEZD PINCER.KEZDES%TYPE;
    CURSOR LEKERD IS SELECT PINCERID, NEV, FIZETES, KOR, KEZDES FROM PINCER;
BEGIN
    OPEN LEKERD;
    LOOP
        FETCH LEKERD INTO P_ID, P_NEV, P_FIZ, P_KOR, P_KEZD;
        EXIT WHEN LEKERD%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(P_ID || ' ' || P_NEV || ' ' || P_FIZ || ' ' || P_KOR || ' ' || P_KEZD);
    END LOOP;
    CLOSE LEKERD;
END;

