--Pincer tabla rekord felvitele
CREATE OR REPLACE PROCEDURE ADDPINCER (PINCID INT, NEV VARCHAR2, FIZETES INT, KOR INT, KEZDES VARCHAR2) IS 
EXSISTERROR EXCEPTION;
rows_found number;

BEGIN
    SELECT COUNT(*) INTO ROWS_FOUND FROM PINCER WHERE PINCERID = PINCID;
    
    IF ROWS_FOUND != 0 THEN RAISE EXSISTERROR;
    ELSE
        INSERT INTO PINCER VALUES(PINCID, NEV, FIZETES, KOR, KEZDES);
    END IF;
EXCEPTION
    WHEN exsisterror THEN
    dbms_output.put_line('Ez az azonosito mar letezik!');
END ADDPINCER;



--Asztal tabla rekord felvitele
CREATE OR REPLACE PROCEDURE ADDASZTAL(ASZTALSZ IN asztal.asztalszam%TYPE, FEROHELY IN asztal.ferohely%TYPE, EMELET IN asztal.emelet%TYPE, FOGLALT IN asztal.foglalt%TYPE, PINCERAZ IN asztal.pinceraz%TYPE) IS 
EXSISTERROR EXCEPTION;
rows_found number;

BEGIN
    SELECT COUNT(*) INTO ROWS_FOUND FROM ASZTAL WHERE ASZTALSZ = ASZTAL.ASZTALSZAM;
    
    IF ROWS_FOUND != 0 THEN RAISE EXSISTERROR;
    ELSE
        INSERT INTO ASZTAL VALUES(ASZTALSZ, FEROHELY, EMELET, FOGLALT, PINCERAZ);
    END IF;
EXCEPTION
    WHEN exsisterror THEN
    dbms_output.put_line('Ez az azonosito mar letezik!');
END ADDASZTAL;



--Pincer tabla modositasa
CREATE OR REPLACE PROCEDURE MODOSITPINCER (ID INT, NAME VARCHAR2) IS 
        notexsisterror exception;
		nameequalerror exception;
		rows_found number;
        current_name char(30);
BEGIN
    SELECT COUNT(*) INTO ROWS_FOUND FROM PINCER WHERE PINCERID = ID;

			IF ROWS_FOUND !=0 THEN
				SELECT NEV INTO CURRENT_NAME FROM PINCER WHERE PINCERID = ID;
			END IF;

			IF ROWS_FOUND = 0 THEN RAISE NOTEXSISTERROR;
			ELSIF 
                NAME = CURRENT_NAME THEN RAISE NAMEEQUALERROR;
			ELSE
				UPDATE PINCER SET NEV = NAME WHERE PINCERID = ID;
			END IF;
		EXCEPTION
			WHEN NOTEXSISTERROR THEN
			DBMS_OUTPUT.PUT_LINE('Ilyen azonositoval nincs pincer!');
			WHEN NAMEEQUALERROR THEN
			DBMS_OUTPUT.PUT_LINE('Ugyanaz a nev van megadva!');
END MODOSITPINCER;



--Asztal tabla rekord modositasa
CREATE OR REPLACE PROCEDURE MODOSITASZTAL(ID INT ,RESERVED INT) IS
NOTEXSISTERROR EXCEPTION;
RESERVEDISNOTVALID EXCEPTION;
rows_found number;

BEGIN

    SELECT COUNT(*) INTO ROWS_FOUND FROM ASZTAL WHERE ASZTALSZAM = ID;
			IF ROWS_FOUND = 0 THEN RAISE NOTEXSISTERROR;
			ELSIF 
                 RESERVED != 1 AND RESERVED != 0 THEN RAISE RESERVEDISNOTVALID;
			ELSE
				UPDATE ASZTAL SET FOGLALT = RESERVED WHERE ASZTALSZAM = ID;
			END IF;
		EXCEPTION
			WHEN NOTEXSISTERROR THEN
			DBMS_OUTPUT.PUT_LINE('Ilyen azonositoval nincs asztal!');
			WHEN RESERVEDISNOTVALID THEN
            DBMS_OUTPUT.PUT_LINE('A megadott adat nem megfelelo');
END MODOSITASZTAL;



--Pincer tabla rekordok torlese
CREATE OR REPLACE PROCEDURE DELETEPINCER(ID INT) IS
NOTEXSISTERROR EXCEPTION;
rows_found number;

BEGIN
   SELECT COUNT(*) INTO ROWS_FOUND FROM PINCER WHERE PINCERID = ID;
    
    IF ROWS_FOUND = 0 THEN RAISE NOTEXSISTERROR;
    ELSE
        DELETE FROM PINCER WHERE PINCERID = ID;
    END IF;
    EXCEPTION
			WHEN NOTEXSISTERROR THEN
			DBMS_OUTPUT.PUT_LINE('Ilyen azonositoval nincs pincer!');
END DELETEPINCER;



--Asztal tabla rekordok torlese
CREATE OR REPLACE PROCEDURE DELETEASZTAL(ID INT) IS
NOTEXSISTERROR EXCEPTION;
rows_found number;

BEGIN
   SELECT COUNT(*) INTO ROWS_FOUND FROM ASZTAL WHERE ASZTALSZAM = ID;
    
    IF ROWS_FOUND = 0 THEN RAISE NOTEXSISTERROR;
    ELSE
        DELETE FROM ASZTAL WHERE ASZTALSZAM = ID;
    END IF;
    EXCEPTION
			WHEN NOTEXSISTERROR THEN
			DBMS_OUTPUT.PUT_LINE('Ilyen azonositoval nincs asztal!');
END DELETEASZTAL;



--Eljarasok futtatasa
EXECUTE ADDPINCER(4, 'Alma Karcsi', 299000, 21, '2022-11-11');
EXECUTE ADDASZTAL(12, 6, 1, 0, 4);
EXECUTE MODOSITPINCER(4, 'Alma Karoly');
EXECUTE MODOSITASZTAL(12, 1);
EXECUTE DELETEASZTAL(12);  --ezt kell eloszor torolni, child adat miatt vagy modositani az asztal pincerID-jat
EXECUTE DELETEPINCER(4);


CREATE TABLE DATA_LOG (DATUM TIMESTAMP, MUVELET VARCHAR2(25), TABLANEV VARCHAR2(25));

SELECT * FROM PINCER;

SELECT * FROM DATA_LOG;

SELECT * FROM ASZTAL;