CREATE OR REPLACE PACKAGE PCKG_ASZTAL IS 
    PROCEDURE ADDASZTAL(ASZTALSZ IN asztal.asztalszam%TYPE, FEROHELY IN asztal.ferohely%TYPE, EMELET IN asztal.emelet%TYPE, FOGLALT IN asztal.foglalt%TYPE, PINCERAZ IN asztal.pinceraz%TYPE);
    PROCEDURE MODOSITASZTAL(ID INT ,RESERVED INT);
    PROCEDURE DELETEASZTAL(ID INT);
    FUNCTION GET_AVG_FEROHELY RETURN NUMBER;
END PCKG_ASZTAL;



--Package body kezdete
CREATE OR REPLACE PACKAGE BODY PCKG_ASZTAL IS 


--Asztal tabla rekord felvitele
PROCEDURE ADDASZTAL(ASZTALSZ IN asztal.asztalszam%TYPE, FEROHELY IN asztal.ferohely%TYPE, EMELET IN asztal.emelet%TYPE, FOGLALT IN asztal.foglalt%TYPE, PINCERAZ IN asztal.pinceraz%TYPE)
IS EXSISTERROR EXCEPTION;
rows_found number;

BEGIN
    SELECT COUNT(*) INTO ROWS_FOUND FROM ASZTAL WHERE ASZTALSZ = ASZTAL.ASZTALSZAM;
    
    IF ROWS_FOUND != 0 THEN RAISE EXSISTERROR;
    ELSE
        INSERT INTO ASZTAL VALUES(ASZTALSZ, FEROHELY, EMELET, FOGLALT, PINCERAZ);
    END IF;
EXCEPTION
    WHEN exsisterror THEN
    dbms_output.put_line('Ez az azonosito mar letezik!');
END;



--Asztal tabla rekord modositasa
PROCEDURE  MODOSITASZTAL(ID INT ,RESERVED INT) IS
NOTEXSISTERROR EXCEPTION;
RESERVEDISNOTVALID EXCEPTION;
rows_found number;

BEGIN

    SELECT COUNT(*) INTO ROWS_FOUND FROM ASZTAL WHERE ASZTALSZAM = ID;
			IF ROWS_FOUND = 0 THEN RAISE NOTEXSISTERROR;
			ELSIF 
                 RESERVED != 1 AND RESERVED != 0 THEN RAISE RESERVEDISNOTVALID;
			ELSE
				UPDATE ASZTAL SET FOGLALT = RESERVED WHERE ASZTALSZAM = ID;
			END IF;
		EXCEPTION
			WHEN NOTEXSISTERROR THEN
			DBMS_OUTPUT.PUT_LINE('Ilyen azonositoval nincs asztal!');
			WHEN RESERVEDISNOTVALID THEN
            DBMS_OUTPUT.PUT_LINE('A megadott adat nem megfelelo');
END;



--Asztal tabla rekordok torlese
PROCEDURE DELETEASZTAL(ID INT) IS
NOTEXSISTERROR EXCEPTION;
rows_found number;

BEGIN
   SELECT COUNT(*) INTO ROWS_FOUND FROM ASZTAL WHERE ASZTALSZAM = ID;
    
    IF ROWS_FOUND = 0 THEN RAISE NOTEXSISTERROR;
    ELSE
        DELETE FROM ASZTAL WHERE ASZTALSZAM = ID;
    END IF;
    EXCEPTION
			WHEN NOTEXSISTERROR THEN
			DBMS_OUTPUT.PUT_LINE('Ilyen azonositoval nincs asztal!');
END;
    
    
    
--Asztal tabla ferohely mezoinek atlaga, mennyi az atlag feohely
FUNCTION GET_AVG_FEROHELY RETURN NUMBER IS AVG_FEROHELY NUMBER;
    
    BEGIN
        SELECT AVG(FEROHELY) INTO AVG_FEROHELY FROM ASZTAL;
        RETURN AVG_FEROHELY;
END;


END;  --end PACKAGE BODY

--Meghivasok

BEGIN
    PCKG_ASZTAL.addasztal(14, 4, 2, 0, 2);
    PCKG_ASZTAL.modositasztal(14, 1);
    PCKG_ASZTAL.deleteasztal(14);
END;

SELECT PCKG_ASZTAL.get_avg_ferohely() FROM dual;
