CREATE OR REPLACE TRIGGER PINCER_TRIGGER
BEFORE INSERT OR DELETE OR UPDATE ON PINCER FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO DATA_LOG VALUES(CURRENT_TIMESTAMP, 'BESZURAS', 'PINCER');
    END IF;
    IF DELETING THEN
        INSERT INTO DATA_LOG VALUES(CURRENT_TIMESTAMP, 'TORLES', 'PINCER');
    END IF;
    IF UPDATING THEN
        INSERT INTO DATA_LOG VALUES(CURRENT_TIMESTAMP, 'MODOSITAS', 'PINCER');
    END IF;
END;

